version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: fx-app-redis
    ports:
      - "6379:6379"
    
  calculator-app:
    image: fx-app:latest
    environment:
      CACHE_REDIS_HOST: redis
      CURRENCY_LAYER_API_KEY: 8dfd321f9ea9666b66c47c8a888cc368
      FIXER_API_KEY: 70bec916792e36fd90edb338cd4f3aca
      LOGGER_COMBINED_FILE_PATH: /var/log/nestjs/combined.log
      LOGGER_ERROR_FILE_PATH: /var/log/nestjs/error.log
    depends_on:
      - redis
    ports:
      - "3000:3000"
